-- Catdome Cup: live database function definitions
-- Captured via pg_get_functiondef() against the production Supabase project
-- (snpnapngocinzpkjeyyn). Each definition below is exactly what's deployed --
-- these came straight from pg_get_functiondef, so they're valid
-- `create or replace function ...` statements as-is.

-- ---- apply_catpoints_ledger_entry ----
CREATE OR REPLACE FUNCTION public.apply_catpoints_ledger_entry()
 RETURNS trigger
  LANGUAGE plpgsql
   SECURITY DEFINER
    SET search_path TO 'public'
    AS $function$
    begin
      if TG_OP in ('INSERT', 'UPDATE') then
          insert into catpoints_balances (team_id, balance, updated_at)
              values (
                    new.team_id,
                          (select coalesce(sum(delta), 0) from catpoints_ledger where team_id = new.team_id),
                                now()
                                    )
                                        on conflict (team_id) do update
                                              set balance = excluded.balance,
                                                        updated_at = now();
                                                          end if;

                                                            if TG_OP = 'DELETE' or (TG_OP = 'UPDATE' and old.team_id is distinct from new.team_id) then
                                                                insert into catpoints_balances (team_id, balance, updated_at)
                                                                    values (
                                                                          old.team_id,
                                                                                (select coalesce(sum(delta), 0) from catpoints_ledger where team_id = old.team_id),
                                                                                      now()
                                                                                          )
                                                                                              on conflict (team_id) do update
                                                                                                    set balance = excluded.balance,
                                                                                                              updated_at = now();
                                                                                                                end if;
                                                                                                                
                                                                                                                  if TG_OP = 'DELETE' then
                                                                                                                      return old;
                                                                                                                        else
                                                                                                                            return new;
                                                                                                                              end if;
                                                                                                                              end;
                                                                                                                              $function$
                                                                                                                              ;
                                                                                                                              
                                                                                                                              -- ---- recompute_all_catpoints_balances ----
                                                                                                                              CREATE OR REPLACE FUNCTION public.recompute_all_catpoints_balances()
                                                                                                                               RETURNS TABLE(out_team_id text, old_balance numeric, new_balance numeric)
                                                                                                                                LANGUAGE plpgsql
                                                                                                                                 SECURITY DEFINER
                                                                                                                                  SET search_path TO 'public'
                                                                                                                                  AS $function$
                                                                                                                                  begin
                                                                                                                                    return query
                                                                                                                                      with correct as (
                                                                                                                                          select cl.team_id as t_id, coalesce(sum(cl.delta), 0) as total
                                                                                                                                              from catpoints_ledger cl
                                                                                                                                                  group by cl.team_id
                                                                                                                                                    ),
                                                                                                                                                      before_balances as (
                                                                                                                                                          select cb.team_id as t_id, cb.balance as old_bal
                                                                                                                                                              from catpoints_balances cb
                                                                                                                                                                ),
                                                                                                                                                                  upserted as (
                                                                                                                                                                      insert into catpoints_balances (team_id, balance, updated_at)
                                                                                                                                                                          select c.t_id, c.total, now()
                                                                                                                                                                              from correct c
                                                                                                                                                                                  on conflict (team_id) do update
                                                                                                                                                                                        set balance = excluded.balance,
                                                                                                                                                                                                  updated_at = now()
                                                                                                                                                                                                      returning catpoints_balances.team_id as t_id, catpoints_balances.balance as new_bal
                                                                                                                                                                                                        )
                                                                                                                                                                                                          select u.t_id, coalesce(b.old_bal, 0), u.new_bal
                                                                                                                                                                                                            from upserted u
                                                                                                                                                                                                              left join before_balances b on b.t_id = u.t_id;
                                                                                                                                                                                                              end;
                                                                                                                                                                                                              $function$
                                                                                                                                                                                                              ;
                                                                                                                                                                                                              
                                                                                                                                                                                                              -- ---- recompute_catpoints_balance ----
                                                                                                                                                                                                              CREATE OR REPLACE FUNCTION public.recompute_catpoints_balance(p_team_id text)
                                                                                                                                                                                                               RETURNS void
                                                                                                                                                                                                                LANGUAGE plpgsql
                                                                                                                                                                                                                 SECURITY DEFINER
                                                                                                                                                                                                                  SET search_path TO 'public'
                                                                                                                                                                                                                  AS $function$
                                                                                                                                                                                                                  begin
                                                                                                                                                                                                                    insert into catpoints_balances (team_id, balance, updated_at)
                                                                                                                                                                                                                      values (
                                                                                                                                                                                                                          p_team_id,
                                                                                                                                                                                                                              (select coalesce(sum(delta), 0) from catpoints_ledger where team_id = p_team_id),
                                                                                                                                                                                                                                  now()
                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                      on conflict (team_id) do update
                                                                                                                                                                                                                                          set balance = excluded.balance,
                                                                                                                                                                                                                                                  updated_at = now();
                                                                                                                                                                                                                                                  end;
                                                                                                                                                                                                                                                  $function$
                                                                                                                                                                                                                                                  ;
                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                  -- ---- trigger_espn_sync ----
                                                                                                                                                                                                                                                  CREATE OR REPLACE FUNCTION public.trigger_espn_sync()
                                                                                                                                                                                                                                                   RETURNS void
                                                                                                                                                                                                                                                    LANGUAGE sql
                                                                                                                                                                                                                                                    AS $function$
                                                                                                                                                                                                                                                      select
                                                                                                                                                                                                                                                          net.http_post(
                                                                                                                                                                                                                                                                url := 'https://snpnapngocinzpkjeyyn.supabase.co/functions/v1/espn-sync',
                                                                                                                                                                                                                                                                      headers := jsonb_build_object(
                                                                                                                                                                                                                                                                              'Content-type', 'application/json',
                                                                                                                                                                                                                                                                                      'apikey', 'sb_publishable_6VolhQsfcvU-UIpDojTO0Q_vY3MpEOs',
                                                                                                                                                                                                                                                                                              'Authorization', 'Bearer sb_publishable_6VolhQsfcvU-UIpDojTO0Q_vY3MpEOs'
                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                          body := '{}'::jsonb
                                                                                                                                                                                                                                                                                                              ) as request_id;
                                                                                                                                                                                                                                                                                                              $function$
                                                                                                                                                                                                                                                                                                              ;
                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                              -- ---- trigger_nfl_lines_grade ----
                                                                                                                                                                                                                                                                                                              CREATE OR REPLACE FUNCTION public.trigger_nfl_lines_grade()
                                                                                                                                                                                                                                                                                                               RETURNS void
                                                                                                                                                                                                                                                                                                                LANGUAGE sql
                                                                                                                                                                                                                                                                                                                AS $function$
                                                                                                                                                                                                                                                                                                                  select net.http_post(
                                                                                                                                                                                                                                                                                                                      url := 'https://snpnapngocinzpkjeyyn.supabase.co/functions/v1/nfl-lines-grade',
                                                                                                                                                                                                                                                                                                                          headers := jsonb_build_object(
                                                                                                                                                                                                                                                                                                                                'Content-type', 'application/json',
                                                                                                                                                                                                                                                                                                                                      'apikey', 'sb_publishable_6VolhQsfcvU-UIpDojTO0Q_vY3MpEOs',
                                                                                                                                                                                                                                                                                                                                            'Authorization', 'Bearer sb_publishable_6VolhQsfcvU-UIpDojTO0Q_vY3MpEOs'
                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                    body := '{}'::jsonb
                                                                                                                                                                                                                                                                                                                                                      ) as request_id;
                                                                                                                                                                                                                                                                                                                                                      $function$
                                                                                                                                                                                                                                                                                                                                                      ;
                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                      -- ---- trigger_nfl_odds_sync ----
                                                                                                                                                                                                                                                                                                                                                      CREATE OR REPLACE FUNCTION public.trigger_nfl_odds_sync()
                                                                                                                                                                                                                                                                                                                                                       RETURNS void
                                                                                                                                                                                                                                                                                                                                                        LANGUAGE sql
                                                                                                                                                                                                                                                                                                                                                        AS $function$
                                                                                                                                                                                                                                                                                                                                                          select
                                                                                                                                                                                                                                                                                                                                                              net.http_post(
                                                                                                                                                                                                                                                                                                                                                                    url := 'https://snpnapngocinzpkjeyyn.supabase.co/functions/v1/nfl-odds-sync',
                                                                                                                                                                                                                                                                                                                                                                          headers := jsonb_build_object(
                                                                                                                                                                                                                                                                                                                                                                                  'Content-type', 'application/json',
                                                                                                                                                                                                                                                                                                                                                                                          'apikey', 'sb_publishable_6VolhQsfcvU-UIpDojTO0Q_vY3MpEOs',
                                                                                                                                                                                                                                                                                                                                                                                                  'Authorization', 'Bearer sb_publishable_6VolhQsfcvU-UIpDojTO0Q_vY3MpEOs'
                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                              body := '{}'::jsonb
                                                                                                                                                                                                                                                                                                                                                                                                                  ) as request_id;
                                                                                                                                                                                                                                                                                                                                                                                                                  $function$
                                                                                                                                                                                                                                                                                                                                                                                                                  ;
                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                  -- ---- trigger_nfl_props_grade ----
                                                                                                                                                                                                                                                                                                                                                                                                                  CREATE OR REPLACE FUNCTION public.trigger_nfl_props_grade()
                                                                                                                                                                                                                                                                                                                                                                                                                   RETURNS void
                                                                                                                                                                                                                                                                                                                                                                                                                    LANGUAGE sql
                                                                                                                                                                                                                                                                                                                                                                                                                    AS $function$
                                                                                                                                                                                                                                                                                                                                                                                                                      select
                                                                                                                                                                                                                                                                                                                                                                                                                          net.http_post(
                                                                                                                                                                                                                                                                                                                                                                                                                                url := 'https://snpnapngocinzpkjeyyn.supabase.co/functions/v1/nfl-props-grade',
                                                                                                                                                                                                                                                                                                                                                                                                                                      headers := jsonb_build_object(
                                                                                                                                                                                                                                                                                                                                                                                                                                              'Content-type', 'application/json',
                                                                                                                                                                                                                                                                                                                                                                                                                                                      'apikey', 'sb_publishable_6VolhQsfcvU-UIpDojTO0Q_vY3MpEOs',
                                                                                                                                                                                                                                                                                                                                                                                                                                                              'Authorization', 'Bearer sb_publishable_6VolhQsfcvU-UIpDojTO0Q_vY3MpEOs'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          body := '{}'::jsonb
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ) as request_id;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              $function$
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              -- ---- trigger_nfl_props_sync ----
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              CREATE OR REPLACE FUNCTION public.trigger_nfl_props_sync()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                               RETURNS void
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                LANGUAGE sql
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                AS $function$
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  select
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      net.http_post(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            url := 'https://snpnapngocinzpkjeyyn.supabase.co/functions/v1/nfl-props-sync',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  headers := jsonb_build_object(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          'Content-type', 'application/json',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  'apikey', 'sb_publishable_6VolhQsfcvU-UIpDojTO0Q_vY3MpEOs',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          'Authorization', 'Bearer sb_publishable_6VolhQsfcvU-UIpDojTO0Q_vY3MpEOs'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      body := '{}'::jsonb,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            timeout_milliseconds := 60000
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ) as request_id;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $function$
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                -- ---- trigger_weekly_recap_post ----
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                CREATE OR REPLACE FUNCTION public.trigger_weekly_recap_post()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 RETURNS void
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  LANGUAGE sql
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  AS $function$
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    select net.http_post(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        url := 'https://snpnapngocinzpkjeyyn.supabase.co/functions/v1/weekly-recap-post',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            headers := jsonb_build_object(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  'Content-type', 'application/json',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'apikey', 'sb_publishable_6VolhQsfcvU-UIpDojTO0Q_vY3MpEOs',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              'Authorization', 'Bearer sb_publishable_6VolhQsfcvU-UIpDojTO0Q_vY3MpEOs'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      body := '{}'::jsonb
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ) as request_id;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        $function$
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
